# Generated by Django 3.1.4 on 2020-12-16 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0004_auto_20201216_1046"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="organisation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.userprofile",
            ),
            preserve_default=False,
        ),
    ]
