# Generated by Django 3.1.4 on 2020-12-17 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0006_auto_20201217_0851"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="organisation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="leads.userprofile",
            ),
        ),
    ]
