# Generated by Django 3.1.4 on 2020-12-17 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0007_category_organisation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="organisation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="leads.userprofile"
            ),
        ),
    ]
