name: 'Workflow :: Pull Request'

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: patch
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env:
        DJANGO_SUPERUSER_USERNAME: admin 
        DJANGO_SUPERUSER_PASSWORD: sekret1
        DJANGO_SUPERUSER_EMAIL: admin@example.com
        MEDEX_APP_USER: medex_app
        MEDEX_APP_PASSWD: MYsuper$passwd123
        MEDEX_APP_DB: medex_app
        MEDEX_APP_DB_HOST: 127.0.0.1
        MEDEX_APP_DB_PORT: 3306
        SECRET_KEY: MEGAPOWERFULLSECRETKEY
        DEBUG: 1
      run: |
        python src/manage.py test
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        black --check .

  sonarcloud:
    needs: [test, format]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
