name: 'Workflow :: Release'

on:
  pull_request:
    types: [ closed ]
  release:
    types: [ published ]

jobs:
  tag:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: minor

# jobs:
#   tag:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       with:
#         fetch-depth: '0'
#     - name: Bump version and push tag
#       uses: anothrNick/github-tag-action@1.36.0
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         WITH_V: true

  # tag:
  #   runs-on: ubuntu-latest
  #   name: Bump-N-Tag Version
  #   steps:
  #   - uses: actions/checkout@master
  #   - name: Increment version
  #     id: version   
  #     uses: vinodhraj/Bump-N-Tag-Version@master
  #     with:
  #       file_name: './VERSION'
  #       tag_version: "true"
  #     env:
  #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  docker:
    needs: tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build & Push to AWS ECR Private
        uses: opspresso/action-docker@master
        with:
          args: --ecr
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "us-east-1"
          TAG_NAME: ${{GITHUB_REF/refs\/tags\//}}
          BUILDX: "true"
          PLATFORM: "linux/amd64"